---
- hosts: all
  become: yes
  gather_facts: no
  tags:
    - always
  tasks:
    - name: repos-dotnet-release
      shell: sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main" > /etc/apt/sources.list.d/dotnetdev.list'
      args:
        chdir:
    - name: apt-key
      shell: apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
      args:
        chdir:
    - apt: update
    - apt: upgrade=safe update_cache=true
    - apt: name={{item}} state=present install_recommends=no
      with_items:
        - git
        - curl
        - libreadline-dev
        - pkg-config
        - autoconf
        - automake
        - build-essential
        - libmysqlclient-dev
        - libssl-dev
        - python3
        - python3-dev
        - python3-venv
        - openjdk-8-jdk-headless
        - libxml2-dev
        - libcurl4-openssl-dev
        - libxslt1-dev
        - re2c
        - bison
        - libbz2-dev
        - libreadline-dev
        - libssl-dev
        - gettext
        - libgettextpo-dev
        - libicu-dev
        - libmhash-dev
        - libmcrypt-dev
        - libgd-dev
        - libtidy-dev
        - dotnet-dev-1.0.0-preview2-003131
